controller:
  replicaCount: 1

broker:
  replicaCount: 0

kraft:
  enabled: true

listeners:
  client:
    protocol: PLAINTEXT

auth:
  clientProtocol: plaintext

provisioning:
  enabled: true
  topics:
    - name: promociones.creadas
      partitions: 1
      replicationFactor: 1

extraConfig: |
  auto.create.topics.enable=false
