apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptador-excel
  namespace: arquisoft-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adaptador-excel
  template:
    metadata:
      labels:
        app: adaptador-excel
    spec:
      containers:
        - name: adaptador-excel
          image: arquisoft/adaptador-excel:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: adaptador-excel-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
