apiVersion: v1
kind: Service
metadata:
  name: adaptador-excel
  namespace: arquisoft-local
spec:
  type: ClusterIP
  selector:
    app: adaptador-excel
  ports:
    - name: http
      port: 8000
      targetPort: 8000
