apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  namespace: arquisoft-local
data:
  MOTOR_NBA_NBO_REPLICAS: http://motor-nba-nbo-0.motor-nba-nbo:8000,http://motor-nba-nbo-1.motor-nba-nbo:8000,http://motor-nba-nbo-2.motor-nba-nbo:8000
  MOTOR_NBA_NBO_TIMEOUT: "10"
