apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: arquisoft-local
spec:
  type: ClusterIP
  selector:
    app: voting
  ports:
    - name: http
      port: 8000
      targetPort: 8000
