apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: arquisoft-local
data:
  COMPONENTE_PROMOCIONES_URL: http://componente-promociones:8000
  MOTOR_NBA_NBO_URL: http://voting:8000
