apiVersion: v1
kind: ConfigMap
metadata:
  name: gestor-promociones-config
  namespace: arquisoft-local
data:
  MONGO_DB: promociones
  MONGO_COLLECTION: promociones
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC_PROMOCIONES_CREADAS: promociones.creadas
