apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-promociones
  namespace: arquisoft-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestor-promociones
  template:
    metadata:
      labels:
        app: gestor-promociones
    spec:
      containers:
        - name: gestor-promociones
          image: arquisoft/gestor-promociones:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gestor-promociones-config
            - secretRef:
                name: gestor-promociones-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
