apiVersion: v1
kind: Secret
metadata:
  name: gestor-promociones-secret
  namespace: arquisoft-local
type: Opaque
stringData:
  MONGO_URI: mongodb://arquisoft:arquisoft@mongo:27017/promociones?authSource=admin
