apiVersion: v1
kind: Service
metadata:
  name: gestor-promociones
  namespace: arquisoft-local
spec:
  type: ClusterIP
  selector:
    app: gestor-promociones
  ports:
    - name: http
      port: 8000
      targetPort: 8000
