apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: arquisoft-local
type: Opaque
stringData:
  POSTGRES_DB: teknoshop_campaigns
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
