apiVersion: v1
kind: Service
metadata:
  name: motor-nba-nbo
  namespace: arquisoft-local
spec:
  type: ClusterIP
  selector:
    app: motor-nba-nbo
  ports:
    - name: http
      port: 8000
      targetPort: 8000
