apiVersion: v1
kind: ConfigMap
metadata:
  name: componente-promociones-config
  namespace: arquisoft-local
data:
  KAFKA_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  KAFKA_TOPIC_PROMOCIONES_CREADAS: promociones.creadas
