apiVersion: v1
kind: Secret
metadata:
  name: componente-promociones-secret
  namespace: arquisoft-local
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/teknoshop_campaigns
